site_name: Alivender's Blog
site_description: 一个技术博客，分享编程和技术心得
site_author: Alivender
# site_url: https://alivenderwww.github.io/

# Theme
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github #右上角图标
    logo: logo
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    # - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - toc.follow
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight
    - search.share
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.code.annotate
    - content.action.edit
    - content.action.view

# Extensions
markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - mdx_truly_sane_lists # 多级列表
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Navigation
nav:
  - 首页: index.md
  - DJIflight:
    - blogs/DJIflight/index.md
    - blogs/DJIflight/algorithm-flow-and-problems.md
  - FPGAWeblab:
    - blogs/FPGA_Weblab/index.md
    - blogs/FPGA_Weblab/01water_led.md
    - blogs/FPGA_Weblab/02key.md
    - blogs/FPGA_Weblab/03led_display.md
    - blogs/FPGA_Weblab/04matrixkey.md
    - blogs/FPGA_Weblab/05pwm.md
    - blogs/FPGA_Weblab/06hdmi.md
    - blogs/FPGA_Weblab/11_password_lock.md
    - blogs/FPGA_Weblab/12_sfp.md
    - blogs/FPGA_Weblab/13_frequency_meter.md
  - 友链: flinks/index.md


# Plugins
plugins:
  - caption
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       shadow: true
       manual: false
       preload: true
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Extra
extra:
  generator: false #是否删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Alivenderwww
    - icon: fontawesome/solid/envelope
      link: mailto:dppp@mail.dlut.edu.cn

extra_javascript:
  # - javascripts/extra.js #自定义javascript
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extra的cdn
  # - ckplayer/js/ckplayer.js #播放器配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js  #gitalk支持
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/copy-tex.min.js
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #忘了

extra_css:
  - stylesheets/extra.css # 自定义CSS
  - stylesheets/link.css #友链配置
  - stylesheets/customize.css # 搜索圆角优化
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css
  # - assets/stylesheets/portfolio.css
  # - stylesheets/video.css #播放器可选配置
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #gitalk支持
  # - ckplayer/css/ckplayer.css   #播放器配置
  # - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesome表情支持
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #分享支持

  - https://cdn.jsdelivr.net/npm/jetbrains-mono@1.0.6/css/jetbrains-mono.min.css # JetBrains Mono 字体
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.7.0/style.css #字体
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.7.0/style.css #字体
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.7.0/style.css  #字体
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.7.0/style.css  #字体
